_target_: pangaea.datasets.dummy.Dummy
dataset_name: Dummy
root_path: /home/gcast/datasets/fix
download_url: None
auto_download: False

img_size: 128
multi_temporal: 6
multi_modal: True
#limited_label: False

# classes
ignore_index: 0
num_classes: 11
# array({'TOMATE': 1, 'CEBOLLA': 2, 'PAPA': 3, 'MELON': 4, 'SAND√çA': 5, 'ZAPALLO': 6, 'POROTO': 7, 'CHOCLO': 8, 'LECHUGA': 9, 'FRUTILLA': 10},

classes:
  - VOID
  - TOMATE
  - CEBOLLA
  - PAPA
  - MELON
  - SANDIA
  - ZAPALLO
  - POROTO
  - CHOCLO
  - LECHUGA
  - FRUTILLA

# {0: np.float64(0.9348012412466654),
#  1: np.float64(0.02784015686531377),
#  2: np.float64(0.007508254632717226),
#  3: np.float64(0.0026982625325520835),
#  4: np.float64(0.0059037247324377545),
#  5: np.float64(0.003841058994696392),
#  6: np.float64(0.008983891184737042),
#  7: np.float64(0.0027377741123602644),
#  8: np.float64(0.004592709425019055),
#  9: np.float64(0.00037613535315040653),
#  10: np.float64(0.0007167909203506098)}
distribution:
  - 0.93480
  - 0.02784
  - 0.00751
  - 0.00270
  - 0.00590
  - 0.00384
  - 0.00898
  - 0.00274
  - 0.00459
  - 0.00038
  - 0.00072


bands:
  optical:
    - B1
    - B2
    - B3
    - B4
    - B5
    - B6
    - B7
    - B8
    - B8A
    - B9
    - B11
    - B12

# Band 0: {'mean': np.float64(3712.8157344084116), 'std': np.float64(3124.1096926653104), 'min': np.uint16(0), 'max': np.uint16(20413)}
# Band 1: {'mean': np.float64(3675.0838115557744), 'std': np.float64(3004.9687523370194), 'min': np.uint16(0), 'max': np.uint16(20768)}
# Band 2: {'mean': np.float64(3649.740605155304), 'std': np.float64(2772.5493397163123), 'min': np.uint16(0), 'max': np.uint16(19408)}
# Band 3: {'mean': np.float64(3596.3506794441037), 'std': np.float64(2689.5027978212356), 'min': np.uint16(0), 'max': np.uint16(18448)}
# Band 4: {'mean': np.float64(3910.958968661342), 'std': np.float64(2693.7198999050775), 'min': np.uint16(0), 'max': np.uint16(17410)}
# Band 5: {'mean': np.float64(4320.756608544327), 'std': np.float64(2416.978427592468), 'min': np.uint16(0), 'max': np.uint16(17184)}
# Band 6: {'mean': np.float64(4453.729154550609), 'std': np.float64(2330.0048447010113), 'min': np.uint16(0), 'max': np.uint16(17058)}
# Band 7: {'mean': np.float64(4506.626791274321), 'std': np.float64(2232.070226900989), 'min': np.uint16(0), 'max': np.uint16(16868)}
# Band 8: {'mean': np.float64(4623.499822621746), 'std': np.float64(2414.9727066892524), 'min': np.uint16(0), 'max': np.uint16(17201)}
# Band 9: {'mean': np.float64(6064.900733430856), 'std': np.float64(4142.25728370343), 'min': np.uint16(0), 'max': np.uint16(16799)}
# Band 10: {'mean': np.float64(3223.930447544832), 'std': np.float64(1441.4347572410777), 'min': np.uint16(0), 'max': np.uint16(16204)}
# Band 11: {'mean': np.float64(2779.1811434944793), 'std': np.float64(1328.5754781065891), 'min': np.uint16(0), 'max': np.uint16(16183)}
data_mean:
  optical:
  - 3712.8157
  - 3675.0838
  - 3649.7406
  - 3596.3506
  - 3910.9589
  - 4320.7566
  - 4453.7291
  - 4506.6267
  - 4623.4998
  - 6064.9007
  - 3223.9304
  - 2779.1811
data_std:
  optical:
  - 3124.1096
  - 3004.9687
  - 2772.5493
  - 2689.5027
  - 2693.7198
  - 2416.9784
  - 2330.0048
  - 2232.0702
  - 2414.9727
  - 4142.2572
  - 1441.4347
  - 1328.5754



data_min:
  optical: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
data_max:
  optical: [20413, 20768, 19408, 18448, 17410, 17184, 17058, 16868, 17201, 16799, 16204, 16183]
